export { default as Layouts } from './layout/Layouts'
export { default as HomePage } from './pages/HomePage'
export { default as ShopingCart } from './pages/ShopingCart'
export { default as Login } from './pages/auth/Login'
export { default as SignUp } from './pages/auth/SignUp'
export { default as Error404Page } from './pages/error/Error404Page'
